### ISSUE TITLE
Error when passing both toDate and fromDate in options()

### ISSUE THREAD

**Issue by roysta2004** [timkpaine/tdameritrade#90]
If I use just toDate, or just fromDate, everything returns as expected.  But when I pass both, I get this error:

Traceback (most recent call last):
  File "D:\tools\Python\lib\site-packages\pandas\core\indexes\base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'tradeTimeInLong'

My code is as follows:

toDate = date.today()+timedelta(days=max_days_to_consider)
fromDate = date.today()+timedelta(days=min_days_to_consider)

tdclient.optionsDF(stock, includeQuotes = True, contractType='PUT', range='OTM', fromDate=fromDate, toDate=toDate)

**Comment by roysta2004** [comment]
I did some more research on this.  OptionsDF does not handle a status back of 'FAILED' from TDA.  It just assumes a success and then tries to convert the columns to datetime, and they do not exist, thus throwing the error.
